# Generated by Django 3.2.4 on 2021-06-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(choices=[('ENCRYPT', 'Encrypt'), ('DECRYPT', 'Decrypt')], default='Encrypt', max_length=7)),
                ('type', models.CharField(choices=[('AESCBC', 'AES CBC'), ('AESCFB', 'AES CFB'), ('OTK', 'One-time Key'), ('BASESF', 'Base 64')], default=None, max_length=15, null=True)),
                ('inputfile', models.FileField(upload_to='inputs/')),
                ('encryptedfile', models.FileField(null=True, upload_to='encrypted/')),
                ('decryptedfile', models.FileField(null=True, upload_to='decrypted/')),
                ('keyfile', models.FileField(null=True, upload_to='')),
                ('ivfile', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
